"""create payment table

Revision ID: 2e2fd16aea03
Revises: 
Create Date: 2026-04-08 22:13:05.748707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2fd16aea03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('payments',
	sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
	sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
	sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='currency_enum'), nullable=False),
	sa.Column('description', sa.String(), nullable=False),
	sa.Column('meta', sa.JSON(), nullable=False),
	sa.Column('status', sa.Enum('PENDING', 'SUCCESSED', 'FAILED', name='status_enum'), nullable=False),
	sa.Column('idempotency_key', sa.UUID(), nullable=False),
	sa.Column('webhook_url', sa.String(length=2048), nullable=False),
	sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
	sa.Column('executed_at', sa.DateTime(), nullable=True),
	sa.PrimaryKeyConstraint('payment_id')
	)
	op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=True)
	op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
	op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
	op.drop_table('payments')
	op.execute("DROP TYPE currency_enum")
	op.execute("DROP TYPE status_enum")
	# ### end Alembic commands ###